# Generated by Django 5.2.5 on 2026-08-20 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0025_expand_surveyattempt_pid'),
        ('vendors', '0019_clientintegration_profile_reuse_first_delay_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='surveyattempt',
            index=models.Index(fields=['-initiated_at'], name='attempt_init_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyattempt',
            index=models.Index(fields=['status', '-initiated_at'], name='attempt_status_init_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyattempt',
            index=models.Index(fields=['platform_user', '-initiated_at'], name='attempt_user_init_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyattempt',
            index=models.Index(fields=['platform_user', 'status', '-initiated_at'], name='attempt_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyattempt',
            index=models.Index(fields=['survey', 'status'], name='attempt_survey_status_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyattempt',
            index=models.Index(fields=['status', '-callback_at'], name='attempt_status_cb_idx'),
        ),
    ]
