# Generated by Django 5.2.5 on 2026-08-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_surveyattempt_attempt_user_init_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattempt',
            name='supplier_api_key_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, editable=False, help_text='API key that issued this respondent entry link, stored without coupling attempt history to key deletion.', null=True),
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='supplier_delivery_config',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Immutable non-secret external-supplier delivery snapshot for this journey.'),
        ),
    ]
