# Generated by Django 5.2.5 on 2026-08-31 09:51

import surveys.models
import uuid
from django.db import migrations, models


def assign_missing_storage_keys(apps, schema_editor):
    ExportJob = apps.get_model("surveys", "ExportJob")
    for job in ExportJob.objects.filter(storage_key="").iterator():
        job.storage_key = f"{uuid.uuid4()}.xlsx"
        job.save(update_fields=["storage_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0034_exportjob'),
    ]

    operations = [
        migrations.RunPython(assign_missing_storage_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exportjob',
            name='storage_key',
            field=models.CharField(default=surveys.models.generate_export_storage_key, editable=False, max_length=80, unique=True),
        ),
    ]
