# Generated by Django 5.2.5 on 2026-08-31

from django.db import migrations, models


def mark_existing_exports_consumed(apps, schema_editor):
    """Do not let historic ready files block a user's first new export."""

    ExportJob = apps.get_model("surveys", "ExportJob")
    ExportJob.objects.filter(status="completed", downloaded_at__isnull=True).update(
        downloaded_at=models.F("finished_at"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0035_alter_exportjob_storage_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportjob",
            name="downloaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_exports_consumed, migrations.RunPython.noop),
    ]
