# Generated by Django 5.2.5 on 2026-09-03 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0036_exportjob_downloaded_at'),
        ('vendors', '0024_raise_rfg_sync_interval_floor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalIDUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_month', models.DateField(db_index=True, help_text='First day of the selected invoice/reconciliation month.')),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(editable=False, max_length=64)),
                ('submitted_count', models.PositiveIntegerField(default=0)),
                ('unique_rid_count', models.PositiveIntegerField(default=0)),
                ('applied_count', models.PositiveIntegerField(default=0)),
                ('not_found_count', models.PositiveIntegerField(default=0)),
                ('client_mismatch_count', models.PositiveIntegerField(default=0)),
                ('not_completed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_id_uploads', to='vendors.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_id_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalIDStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, max_length=10)),
                ('accounting_month', models.DateField(db_index=True, help_text='Invoice month selected for the most recent client decision.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_id_status', to='surveys.surveyattempt')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_id_statuses', to='vendors.client')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_statuses', to='surveys.finalidupload')),
            ],
        ),
        migrations.CreateModel(
            name='FinalIDUploadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(db_index=True, max_length=10)),
                ('outcome', models.CharField(choices=[('applied', 'Applied'), ('not_found', 'RID not found'), ('client_mismatch', 'RID belongs to another client'), ('not_completed', 'RID is not a completed journey')], db_index=True, max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=10)),
                ('applied_status', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_id_upload_items', to='surveys.surveyattempt')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='surveys.finalidupload')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='finalidupload',
            index=models.Index(fields=['client', 'accounting_month', '-created_at'], name='surveys_fin_client__2af55b_idx'),
        ),
        migrations.AddIndex(
            model_name='finalidstatus',
            index=models.Index(fields=['client', 'status', 'accounting_month'], name='surveys_fin_client__155ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='finaliduploaditem',
            index=models.Index(fields=['upload', 'outcome'], name='surveys_fin_upload__d53983_idx'),
        ),
        migrations.AddIndex(
            model_name='finaliduploaditem',
            index=models.Index(fields=['rid', '-created_at'], name='surveys_fin_rid_7f52ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='finaliduploaditem',
            constraint=models.UniqueConstraint(fields=('upload', 'rid'), name='unique_final_id_upload_rid'),
        ),
    ]
