# Generated by Django 5.2.5 on 2026-08-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_clientintegration_profile_reuse_first_delay_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapikey',
            name='callback_secret_last_four',
            field=models.CharField(blank=True, editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='callback_signing_enabled',
            field=models.BooleanField(default=False, help_text='Append an HMAC-SHA256 hash to callbacks sent to this supplier.'),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='complete_callback_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='encrypted_callback_secret',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='quality_callback_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='quota_callback_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='survey_id_mode',
            field=models.CharField(choices=[('project_id', 'Project ID (recommended)'), ('provider_survey_id', 'Provider survey ID')], default='project_id', help_text="Controls which identifier is exposed as survey_id in this key's inventory.", max_length=24),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='terminate_callback_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
