# Generated by Django 5.2.5 on 2026-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_vendorapikey_callback_secret_last_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorapikey',
            name='client_allocations',
            field=models.ManyToManyField(blank=True, help_text='Client grants this key may expose. Per-project access exclusions still follow the live allocation rules.', related_name='api_keys', to='vendors.vendorclientallocation'),
        ),
    ]
